version: '3'

services:
  backend:
    build:
      context: './Back End'
    depends_on:
      - database
    ports:
      - 8000
  frontend:
    build:
      context: './Front End'
    depends_on:
      - backend
  proxy:
    build:
      context: ./Proxy
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  database:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=onlinetechdatastore
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
volumes:
  db_volume:
